source "https://rubygems.org"

gem "rails", "~> 5.0.0", ">= 5.0.0.1"
gem "mysql2", ">= 0.3.18", "< 0.5"
gem "puma", "~> 3.0"
gem "sass-rails", "~> 5.0"
gem "bootstrap-sass", "~> 3.3.6"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.2"
gem "jquery-rails"
gem "turbolinks", "~> 5"
gem "jbuilder", "~> 2.5"
gem "devise"
gem "cancancan", "1.10"
gem "paranoia", "~> 2.2.0.pre"
gem "kaminari"
gem "bootstrap-kaminari-views"
gem "config"
gem "bootstrap-glyphicons"
gem "font-awesome-rails"
gem "simple_form"
gem "dropzonejs-rails"
gem "carrierwave",             "0.10.0"
gem "mini_magick",             "3.8.0"
gem "cloudinary"
gem "adminlte2-rails"
gem "figaro"
gem "activemodel-serializers-xml", github: "rails/activemodel-serializers-xml"
gem "draper", github: "audionerd/draper", branch: "rails5"
gem "jquery-turbolinks"
gem "acts-as-taggable-on", "~> 4.0"
gem "bootstrap-tagsinput-rails"
gem "social-share-button"
gem "chartkick"
gem "ransack"
gem "daemons"
gem "delayed_job"
gem "roo"
gem "roo-xls"
gem "delayed_job_active_record"
gem "rails-i18n", "~> 5.0.0"
gem "i18n-js", ">= 3.0.0.rc11"
gem "simple_token_authentication", "~> 1.0"
gem "versionist"
gem "active_model_serializers", "~> 0.10.0"
gem "actionpack-page_caching"
gem "animate-rails"
gem "validates_timeliness"
gem "jquery-validation-rails"
gem "sweet-alert-confirm"
gem "axlsx_styler"
gem "chatwork"
gem "acts_as_follower", github: "tcocca/acts_as_follower"

source "https://rails-assets.org" do
  gem "rails-assets-datetimepicker"
  gem "rails-assets-growl"
end
gem "omniauth-facebook"
gem "omniauth-google-oauth2"
gem "omniauth"
gem "json"
gem "friendly_id", "~> 5.1.0"
gem "ratyrate"
gem "redis", "~> 3.0"
gem "fcm"
gem "strip_attributes"
gem "carrierwave-base64"
gem "zip-zip"
gem "axlsx", "2.1.0.pre"
gem "axlsx_rails", "> 0.4"
gem "omniauth-hrsystem", git: "https://github.com/framgia-education/omniauth-hrsystem.git"

group :development, :test do
  gem "byebug", platform: :mri
  gem "factory_girl_rails"
  gem "rspec-rails", "~> 3.5"
  gem "pry"
  gem "faker"
end

group :development do
  gem "web-console"
  gem "listen", "~> 3.0.5"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "spring-commands-rspec"
  gem "pry-rails"
  gem "bullet"
end

group :test do
  gem "rspec-activemodel-mocks"
  gem "database_cleaner"
  gem "shoulda-matchers", "3.0.1"
  gem "simplecov"
  gem "rails-controller-testing"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
